# =============================================================================
# GOOGLE / GEMINI API
# =============================================================================
google_api_key = "AIzaSyAydGcy_-neBkcldbyVmHjF3GGW_ET54zY"

# =============================================================================
# CLOUDFLARE R2 CONFIGURATION
# =============================================================================
[cloudflare_r2]
account_id = "229f2ce2ce6bb0283b3edc7ad6c0ecbe"
endpoint_url = "https://229f2ce2ce6bb0283b3edc7ad6c0ecbe.r2.cloudflarestorage.com"
access_key_id = "755ae62d212b1c9a565894d9a44a6783"
secret_access_key = "7ca457fdf792678d8c2212244ea9aafa1c4cb2d51ada73e290fb55d109419cb5"
public_base_url = "https://pub-3de23488ca6c4e2392d96de04f8c5cff.r2.dev"

# =============================================================================
# GCP SERVICE ACCOUNT
# =============================================================================
[gcp_service_account]
type = "service_account"
project_id = "woven-edge-480010-a0"
private_key_id = "271890b9d5ac5142169546575d58e8377bb16950"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC2tj9haftQChrt
5xfwbOe9OKZnpIszKJNgoYvsCd8f5EHQdG8Gfwbt7kZkpaSB+thVymCAwIN5sVK8
4F5mjT/plpt5uju8naQqzbJeLMPPyYbiWYMLtTKtC1teSJwfcj4Sm4JC9U4FH8Ck
StCEP/xyhBJKF2shC6L2Rm1boJmG63WXTPBNAGYjH1eX19SHgfqrBF82Ug8ioFzc
m5NBRECvng/iUCDoEATGFKxprpv1A4C1jZNwfrSyXweGMwIbv+tntcMBWc3kujCD
ecNEMB9ARxJBpXQxQq2ocvRpZUHxerGAQT6JvSKgQ0biUg7bkiYg5ZnaPCgHK1MM
ttuHYIDxAgMBAAECggEAA5bMnIl0OXl4AjrYd0nhQgjtplNENUp41m5KZEJzDIGF
UKpQaB3J8weaAI4ST1Yay9jYcLjMtwY4Rhkmh8oCr/kN3dl3JP3iv12AMylwHc5u
7avwhGsbwPp/07gpzn7iaxjgTrR27ZLIr33xu1tSFJd1ZYOw+Tqe3y5Os8sYy56R
Aa4eqqIWI835JvwcWocB4ZGuRmbVcMO8X3L2BWagb2v7vJu2RRZnjkXt44U7FSFC
LctGcYFQk64TDV3iY2hMjlPyni/mtKOEK8FZ1nhj/VQXrJtTlW/F/Ki73ruLKg3U
FDZZliu2tIjGgH1cJMmCzxIDPpsNg6+bBgci8Z08HQKBgQDYRpM7STkNbJZM7Mv4
NN/MSbXYgIr/EDMQxRtfbYqOBA9sHUIgVSIY4vvM3+lpECRdeX9C5TtLXnOa/qha
6QnkkEnANIlAQyrejbfoon/8QTsnp3GWkHi6cGP2AuiWPqnQXr5TFsb0RbZetnqD
rmHgCVvXnmI1vacB8MnfhBUrbQKBgQDYRXtCDCycDZhpcrkipt2leXBc4Os5qyyi
1AcQ8Erq9BQhFK3j9NZF8dwVuE/kR5BKWWE6rMCf/JuvohLt9H4T+VIX0aIUskT1
RaS5o/Iv5oVsM1ak8Lrc/PRNcmhuERYcOMlFoys2RnVvRkz/QHU68gGeGIGaSjje
s5JVaOQVFQKBgBtUv+JsHHOf11adTiFtvSJ55isYA3i8OVfTMORcWXgc9z34bJTd
bVOry5pWaY7HZXESm4x+n4GkzAM4T1o9vOxPd6J8gSPH2TEKw8T4VCgyriESvf4C
/96/uUIrl+z0uk0EzBR/+mCANs29Tbo6XVAMnrie4VZdQy+xmDFQ5cP5AoGAQnY3
xrhPDTXwXJdw5YE6JBwJt8E3CGXeNbvK4B24KDQR64ibV65qGtyUsegORSzo3rBQ
/OMR3xiWD4dTIeU8yY6Y99DoakvOfUGFubb0OlwxLGsqeU2xXzAtM4+xIAIINWwO
DmRyZx+H/0Yva1G3tQGiFZ+aVHvyth2hHrY5QXECgYEAujF/Fh1KUV5YVhc9T84G
jKYD4xnUTwHRUjgvUchxTAT9sTdcz+VIBpF1LzdNYZMa3HwQ5Bpy//UWL0sClOlX
WGh7J0FVUkCEw74TjQcAPBgQWIDuD+lwUNEHZgSsCn2HVZnip1WbkluMyj2i9hN4
f0gSu8GMfI3BcTBya+vZ0UA=
-----END PRIVATE KEY-----"""
client_email = "data-download@woven-edge-480010-a0.iam.gserviceaccount.com"
client_id = "112324057968017467917"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/data-download%40woven-edge-480010-a0.iam.gserviceaccount.com"

# =============================================================================
# USER CONFIGURATIONS
# =============================================================================
[users.Adnak]
password = "akshay1"
r2_bucket = "adnak-sir-invoices"
sheet_id = "1741gK1V-MQlr3CE3ldkyDh26jbGe7r8CKCSkUCm2Pbg"
dashboard_url = "https://lookerstudio.google.com/reporting/2c91f3c2-92cb-44c0-9bf5-b4697caadaf0"

[users.pradeep]
password = "abcd"
r2_bucket = "pradeep-invoices"
sheet_id = "PUT_YOUR_SHEET_ID_IF_USED"
dashboard_url = "https://lookerstudio.google.com/reporting/..."

[users.user1]
password = "pass123"
r2_bucket = "user1-invoices-2024"
sheet_id = "1741gK1V-MQlr3CE3ldkyDh26jbGe7r8CKCSkUCm2Pbg"
dashboard_url = "https://lookerstudio.google.com/reporting/YOUR_DASHBOARD"

# =====================================================
# SUPABASE CONFIGURATION
# =====================================================
[supabase]
url = "https://zlqwoexomqggkigjalds.supabase.co/"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpscXdvZXhvbXFnZ2tpZ2phbGRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY4OTk1ODYsImV4cCI6MjA4MjQ3NTU4Nn0.eUze-cGOkiYCihYXUSI-xguIQp1UEMPCItk8cX1v4Ac"
service_role_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpscXdvZXhvbXFnZ2tpZ2phbGRzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2Njg5OTU4NiwiZXhwIjoyMDgyNDc1NTg2fQ.l12clHHyjkDu8ernU--3BabtJZTP41yAzKKtF0NHEFE"